### ISSUE TITLE
seo_pro - Не совсем ошибка

### ISSUE THREAD

**Issue by chulcha** [myopencart/ocStore#151]
seo_pro

$path = $this->getPathByProduct($this->request->get['product_id']);

запрос в методе

private function getPathByProduct($product_id) {

$query = $this->db->query("SELECT category_id FROM " . DB_PREFIX . "product_to_category WHERE product_id = '" . $product_id . "' ORDER BY main_category DESC LIMIT 1");

Страшного ничего нет
1. метод приватный
2 экранирование product_id есть, но не явное

$product_id = (int)$product_id;

Минус такого запроса, что можно скопировать и куда-то вставить без экранирования

**Comment by shoputils** [comment]
В самой первой строке метода: $product_id = (int)$product_id;
Поэтому экранирование есть. Если кто-то будет бездумно копипастить, то это исключительно его головная боль (голова нужна не только, чтобы в нее есть).

**Comment by sergiosinicin** [comment]
ну конечно трудно наверное поставить (int) в самом запросе

**Comment by sergiosinicin** [comment]
ну конечно ,трудно поставить (int) в самом запросе

**Comment by chulcha** [comment]
Потому что это культура кода БАЗОВОГО функционала!
