### ISSUE TITLE
Undefined variable: username

### ISSUE THREAD

**Issue by crimerrsplay** [myopencart/ocStore#154]
Undefined variable: username in /admin/view/template/common/column_left.tpl on line 5

`<img src="<?php echo $image; ?>" alt="<?php echo $firstname; ?> <?php echo $lastname; ?>" title="<?php echo $username; ?>" class="img-circle" />`

**Comment by shoputils** [comment]
https://github.com/myopencart/ocStore/commit/3cfa73fd057b45f7f17d4d12f30f9a3b9e994e6b
