### ISSUE TITLE
исправление ?page={page} в пагинации

### ISSUE THREAD

**Issue by AlexDWZ** [myopencart/ocStore#157]
исправление бага с пагинацией - **?page={page}** вместо номера страницы

обсуждалось [здесь](https://opencartforum.com/topic/49053-seo_pro-dlya-opencart/?do=findComment&comment=643533)
[коммит](https://github.com/eka7a/opencart/commit/86de3866f572bc0f5d2ad193148fdd9890a9da1c)

**Comment by dinoxtech** [comment]
Исправлено
