### ISSUE TITLE
файл system/track_no-oc2.3.x.ocmod.xml

### ISSUE THREAD

**Issue by ShkiperOK** [myopencart/ocStore#160]
файл system/track_no-oc2.3.x.ocmod.xml

1. строка 102

нет закрывающего тега </file>

2. строка 135-136

удалить лишний текст

<b><?php echo $text_shipping_method; ?></b> <?php echo $shipping_method; ?>            
    </file>

**Comment by AlexDWZ** [comment]
[2 месяца назад еще](https://github.com/myopencart/ocStore/commit/43b5a302751ce935f5cca886ef34d7a6715072ae)
в ветку dev чаще заглядывайте ;-)
