### ISSUE TITLE
При поиске с учетом категории, вместо поиска редиректит на выбраную категорию

### ISSUE THREAD

**Issue by pashast** [myopencart/ocStore#163]
в предыдущих версиях была проверка
![Alt text](https://monosnap.com/file/vzbXMjIJQbQL5dPCwQWIQlstA8O80L.png)
в 2.3 ее убрали
с какой-то целью или просто случайно?

**Comment by dinoxtech** [comment]
Да ошибочно 
https://github.com/myopencart/ocStore/commit/578b7243365e17196b81016246f58da4119871b0
