### ISSUE TITLE
исправление Fatal error: SessionHandler::create_sid()

### ISSUE THREAD

**Issue by AlexDWZ** [myopencart/ocStore#164]
описано [здесь](https://opencartforum.com/topic/72527-oshibka-pri-zahode-na-sayt-fatal-error-sessionhandlercreate_sid/), там же ссылка на коммит

**Comment by shoputils** [comment]
https://github.com/myopencart/ocStore/commit/45303b6ea9ebc02389f96cc7aa73834d1b1aafee
