### ISSUE TITLE
PHP Error Ошибка при отправке email через SMTP

### ISSUE THREAD

**Issue by partizzzzzan** [myopencart/ocStore#94]
Ошибка возникает при отправке письма со странице обратной связи, при регистрации нового клиента. Наблюдалась не у всех, есть подозрение, что зависит от хостера. Удалось исправить следующим способом
Файл
`system/library/mail.php`
Находим
`'MAIL FROM: <' . $this->from`
Заменяем на
`'MAIL FROM: <' . $this->smtp_username`

**Comment by shoputils** [comment]
Не стоит так делать. Не все используют SMTP.

**Comment by partizzzzzan** [comment]
Извиняюсь, забыл написать, что действительно использовал SMTP.
Но данное решение исправило ошибку при отправке почты по SMTP
