### ISSUE TITLE
Не удаляется товар из корзины, при включеном модуле SeoPro.

### ISSUE THREAD

**Issue by ghost** [myopencart/ocStore#96]
Не удаляется товар из корзины, при включеном модуле SeoPro. После нажатия на крестик удаления товара из корзины товар не удаляется, сумма заказа не пересчитывается до обновления страницы.
Текущая сборка ocStore 2.1.0.2 (чистая, без правок).

**Comment by Pegalet** [comment]
Пофиксили в #132
