### ISSUE TITLE
Ошибка в api (api/order)

### ISSUE THREAD

**Issue by chulcha** [myopencart/ocStore#98]
проверка на наличие полей а post запросе
`
    public function history() {
        $this->load->language('api/order');

```
    $json = array();

    if (!isset($this->session->data['api_id'])) {
        $json['error'] = $this->language->get('error_permission');
    } else {
        // Add keys for missing post vars
        $keys = array(
            'order_status_id',
            'notify',
            'append',
            'comment'
        );
```

`
Но при этом
`$this->model_checkout_order->addOrderHistory($order_id, $this->request->post['order_status_id'], $this->request->post['comment'], $this->request->post['notify'], $this->request->post['override']);`

т.е. не проверяется наличие override

**Comment by dinoxtech** [comment]
Исправлено в оригинале 2.3
